# Generated by Django 5.1.2 on 2024-12-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_contactmessage_courses_fee_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstaffs',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
